### ISSUE TITLE
Challenges deploying application in non-default namespace

### ISSUE THREAD

**Issue by distortedsignal** [DickChesterwood/istio-fleetman#44]
I was working in the Udemy course (GREAT course BTW) and trying to deploy the app in a non-`default` namespace, and I was getting a 500 error when I was trying to access the webapp. I then un-apply-ed the services from the non-`default` namespace and applied them to the `default` namespace, and the app worked perfectly. I think the issue that I'm seeing is in some of the configmaps where you've got lines like these:
```
value: kubernetes://apis/{{ .TypeMeta.APIVersion }}/namespaces/{{ valueOrDefault .DeploymentMeta.Namespace `default` }}/{{ toLower .TypeMeta.Kind}}s/{{ .DeploymentMeta.Name }}
```
I'm not totally familiar with K8s, but it might be that the namespace there is getting filled in as default instead of the namespace that the deployment is in. I'll let you troubleshoot this.

I want to say those are lines 17463 and 17618 in `2-istio-minikube.yaml`. However, there are more than 200 instances of the word `namespace` in that file, so it's _very possible_ that I missed where the actual problem is.

Critical versions and stuff:
```sh
> minikube version
minikube version: v1.14.2
commit: 2c82918e2347188e21c4e44c8056fc80408bce10
```
```sh
> kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:08:32Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```
*.tar.gz of the telemetry directory in the downloads of the course: 
[Telemetry.tar.gz](https://github.com/DickChesterwood/istio-fleetman/files/5534428/Telemetry.tar.gz)

Minimal repro path:
1. Install minikube
2. `minikube start --memory 4096`
3. `kubectl create ns telemetry`
4. `kubectl label ns telemetry istio-injection=enabled`
5. In your kubeconfig file (wherever that may be) add a section like the following:
```yaml
- context:
    cluster: minikube
    user: minikube
    namespace: telemetry
  name: minikube-telemetry
```
6. `kubectl config use-context minikube-telemetry`
7. Un-tar the files linked above and cd into the new directory
8. `kubectl apply -f 1-istio-init.yaml`
9. `kubectl apply -f 2-istio-minikube.yaml`
10. `kubectl apply -f 3-kiali-secret.yaml`
11. We can skip applying `4-label-default-namespace.yaml` because we did that for our new namespace in step 4.
12. `kubectl apply -f 5-application-no-istio.yaml`

At this point, all the pods should come up successfully. Everything initializes successfully, everything comes up. No crash loop backoff or anything. Your system should look like this:
```sh
> kubectl config get-contexts
CURRENT   NAME                 CLUSTER    AUTHINFO     NAMESPACE
...
          minikube             minikube   minikube
*         minikube-telemetry   minikube   minikube     telemetry
> kubectl get all
NAME                                     READY   STATUS    RESTARTS   AGE
pod/api-gateway-6f87d9477f-dn4kd         2/2     Running   0          2m57s
pod/position-simulator-f6896665b-57lgq   2/2     Running   0          2m52s
pod/position-tracker-5b767bb48b-8drz7    2/2     Running   0          2m51s
pod/staff-service-74587b6b98-gpgx9       2/2     Running   0          2m50s
pod/vehicle-telemetry-77dfb44c6d-gsftf   2/2     Running   0          2m50s
pod/webapp-6bb5c7b569-98c5l              2/2     Running   0          2m50s

NAME                                 TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE
service/fleetman-api-gateway         ClusterIP   10.106.6.181   <none>        8080/TCP       3m46s
service/fleetman-position-tracker    ClusterIP   10.99.86.62    <none>        8080/TCP       3m46s
service/fleetman-staff-service       ClusterIP   10.111.41.9    <none>        8080/TCP       3m46s
service/fleetman-vehicle-telemetry   ClusterIP   10.105.16.26   <none>        8080/TCP       3m46s
service/fleetman-webapp              NodePort    10.109.11.26   <none>        80:30080/TCP   3m46s

NAME                                 READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/api-gateway          1/1     1            1           3m46s
deployment.apps/position-simulator   1/1     1            1           3m46s
deployment.apps/position-tracker     1/1     1            1           3m46s
deployment.apps/staff-service        1/1     1            1           3m46s
deployment.apps/vehicle-telemetry    1/1     1            1           3m46s
deployment.apps/webapp               1/1     1            1           3m46s

NAME                                           DESIRED   CURRENT   READY   AGE
replicaset.apps/api-gateway-6f87d9477f         1         1         1       3m46s
replicaset.apps/position-simulator-f6896665b   1         1         1       3m46s
replicaset.apps/position-tracker-5b767bb48b    1         1         1       3m46s
replicaset.apps/staff-service-74587b6b98       1         1         1       3m46s
replicaset.apps/vehicle-telemetry-77dfb44c6d   1         1         1       3m46s
replicaset.apps/webapp-6bb5c7b569              1         1         1       3m46s
```
So that all looks great.

But when we go to the browser and check the app...
```sh
> minikube ip
192.168.99.100
```
And the site looks like this:
<img width="1635" alt="Screen Shot 2020-11-12 at 7 11 04 PM" src="https://user-images.githubusercontent.com/2186874/99024183-e1a50d80-251a-11eb-9844-cbab5a984b2c.png">

The error at the bottom is _very_ hard to capture because it vanishes very quickly. It looks like it says
```
Error code 500 occured.
fleetman-position-tracker.default.svc.cluster.local executing GET http://fleetman-position-tracker.default.svc.cluster.local:8080/vehicles/City%20Truck
```
Let me know if you have trouble replicating this.

**Comment by DickChesterwood** [comment]
Sorry I didn't see this issue raised, usually I get a notification from github. Don't forget you can always open a Q&A at Udemy.

It's my bad this. I ported the system from the original Kubernetes course, and in doing so I forgot that I had left a hardcoded reference to the namespace in the URL used  - it uses the FQDN and so it includes "default". (fleetman-position-tracker.default.svc.cluster.local)

So the only way to deploy the app is by using the default namespace. OR you could rebuild the images and change to just the service name (which I should have done in the first place!)

Sorry about that, I would fix it myself BUT I'm faro to scared to touch the images as I risk breaking the course for everyone!
