### ISSUE TITLE
Add support for Ambassador

### ISSUE THREAD

**Issue by s-bhupathiraju** [DickChesterwood/istio-fleetman#7]
I'd imagine at some point you want to use this code as a reference to your future courses on Istio. Could you add support for Ambassador as the API gateway instead?

**Comment by DickChesterwood** [comment]
Yes I'm slowly working on this project as a sample app for Istio. I doubt I'll get round to bringing in Ambassador this time around but I'll definitely be looking at covering that somewhere in the future, thanks for the prompt.
